### ISSUE TITLE
Docker Path for config?

### ISSUE THREAD

**Issue by Eric-sson** [Gyarbij/Plexist#64]
What is the docker path I would need to enter to save my config (appdata)?

**Comment by Gyarbij** [comment]
`volumes:
      - ./plexist_data:/app/data`

You can use whatever host path you like. The dev branch has better support in that both the db and csv would be stored there.

**Comment by Eric-sson** [comment]
@Gyarbij 

I switched to dev branch and setup the docker container as following:

services:
  plexist:

    command:
      - "python"
      - "plexist/plexist.py"

    container_name: "plexist"

    environment:
      - "HOST_OS=Unraid"
      - "ADD_PLAYLIST_POSTER=1"
      - "SECONDS_TO_WAIT=604800"
      - "SPOTIFY_CLIENT_SECRET=xxxx"
      - "HOST_HOSTNAME=Tower"
      - "PLEX_URL=http://192.168.4.158:32400"
      - "PLEX_TOKEN=xxxx"
      - "WRITE_MISSING_AS_CSV=1"
      - "APPEND_INSTEAD_OF_SYNC=1"
      - "HOST_CONTAINERNAME=plexist"
      - "PUID=99"
      - "SPOTIFY_CLIENT_ID=xxxx"
      - "SPOTIFY_USER_ID=xxxx"
      - "TZ=Europe/Paris"
      - "ADD_PLAYLIST_DESCRIPTION=1"
      - "PGID=100"
      - "UMASK=002"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.12.5"
      - "PYTHON_PIP_VERSION=24.2"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66d8a0f637083e2c3ddffc0cb1e65ce126afb856/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=6fb7b781206356f45ad79efbb19322caa6c2a5ad39092d0d44d0fec94117e118"
      - "PYTHONDONTWRITEBYTECODE=1"
      - "PYTHONUNBUFFERED=1"

    hostname: "dd867eff32f5"

    image: "gyarbij/plexist:dev"

    ipc: "private"

    labels:
      net.unraid.docker.icon: "https://github.com/Gyarbij/Plexist/blob/main/assets/plexist.png"
      net.unraid.docker.managed: "dockerman"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    user: "plexist"

    volumes:
      - "/mnt/cache/appdata/plexist:/plexist_data"

    working_dir: "/app"

version: "3.6"

It will not create anything in the folder plexist (no db or csv). It will run and match songs but after while exits with below error:

File "/usr/local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.4.158', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 285, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 125, in _get_available_plex_tracks
    results = list(executor.map(match_track, tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 122, in match_track
    return _match_single_track(plex, track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 204, in _match_single_track
    match, score = search_and_score(query, 0.85)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 167, in search_and_score
    search = plex.search(query, mediatype="track", limit=20)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 804, in search
    for hub in self.fetchItems(key, Hub):
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/base.py", line 281, in fetchItems
    data = self._server.query(ekey, headers=headers, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 760, in query
    response = method(url, headers=headers, params=params, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.4.158', port=32400): Read timed out. (read timeout=30)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 105, in <module>
    main()
  File "/app/plexist/plexist.py", line 88, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 81, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14a2b25a60f0 state=finished raised ReadTimeout>]

Is there anything that I am missing or incorrectly setup?

**Comment by Gyarbij** [comment]
Hi @Eric-sson first and asap, please invalidate the plex token and spotify client secret. Just create new ones as you've exposed sensitive info.

Also with your setup you did nothing wrong, i forgot to include that you need to set `DB_PATH=` as an environment variable.

Please see this example:

```
services:
  plexist:
    image: gyarbij/plexist:dev
    environment:
      - DB_PATH=/data/plexist.db  # Define the database path
      - WRITE_MISSING_AS_CSV=1 
      - CSV_PATH=/data/exported.csv 
    volumes:
      - ./data:/data  # set to anywhere you/docker have permission to access
```

**Comment by Eric-sson** [comment]
@Gyarbij 

I have added the paths as you advised me. See below.

services:
  plexist:

    command:
      - "python"
      - "plexist/plexist.py"

    container_name: "plexist"

    environment:
      - "SPOTIFY_CLIENT_SECRET=xxx"
      - "TZ=Europe/Paris"
      - "APPEND_INSTEAD_OF_SYNC=1"
      - "UMASK=002"
      - "ADD_PLAYLIST_DESCRIPTION=1"
      - "SECONDS_TO_WAIT=604800"
      - "PGID=100"
      - "SPOTIFY_CLIENT_ID=xxx"
      - "HOST_HOSTNAME=Tower"
      - "PLEX_TOKEN=xxx"
      - "ADD_PLAYLIST_POSTER=1"
      - "HOST_CONTAINERNAME=plexist"
      - "WRITE_MISSING_AS_CSV=1"
      - "PUID=99"
      - "HOST_OS=Unraid"
      - "PLEX_URL=http://192.168.4.158:32400"
      - "SPOTIFY_USER_ID=xxx"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.12.5"
      - "PYTHON_PIP_VERSION=24.2"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66d8a0f637083e2c3ddffc0cb1e65ce126afb856/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=6fb7b781206356f45ad79efbb19322caa6c2a5ad39092d0d44d0fec94117e118"
      - "PYTHONDONTWRITEBYTECODE=1"
      - "PYTHONUNBUFFERED=1"

    hostname: "c8fd112b0b81"

    image: "gyarbij/plexist:dev"

    ipc: "private"

    labels:
      net.unraid.docker.icon: "https://github.com/Gyarbij/Plexist/blob/main/assets/plexist.png"
      net.unraid.docker.managed: "dockerman"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    user: "plexist"

    volumes:
      - "/mnt/cache/appdata/missings:/CSV_PATH"
      - "/mnt/cache/appdata/plexist/plexist.db:/DB_PATH"
      - "/mnt/cache/appdata/plexist:/plexist_data"

    working_dir: "/app"

version: "3.6"

But I am now getting the below message. After that the container stops.

Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 109, in <module>
    main()
  File "/app/plexist/plexist.py", line 72, in main
    initialize_db()
  File "/app/plexist/modules/plex.py", line 29, in initialize_db
    conn = sqlite3.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 109, in <module>
    main()
  File "/app/plexist/plexist.py", line 72, in main
    initialize_db()
  File "/app/plexist/modules/plex.py", line 29, in initialize_db
    conn = sqlite3.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

I checked permissions and they are all fine for the folder plexist and db file within that folder.
Anything that I am missing?

**Comment by Gyarbij** [comment]
EDIT: Try the following, i think I see the issue where you did not include the env `DB_PATH`, not familiar what unraid so took a while;

```
command:
  - "python"
  - "plexist/plexist.py"

container_name: "plexist"

environment:
  - "DB_PATH=/data/plexist.db"
  - "SPOTIFY_CLIENT_SECRET=xxx"
  - "TZ=Europe/Paris"
  - "APPEND_INSTEAD_OF_SYNC=1"
  - "UMASK=002"
  - "ADD_PLAYLIST_DESCRIPTION=1"
  - "SECONDS_TO_WAIT=604800"
  - "PGID=100"
  - "SPOTIFY_CLIENT_ID=xxx"
  - "HOST_HOSTNAME=Tower"
  - "PLEX_TOKEN=xxx"
  - "ADD_PLAYLIST_POSTER=1"
  - "HOST_CONTAINERNAME=plexist"
  - "WRITE_MISSING_AS_CSV=1"
  - "PUID=99"
  - "HOST_OS=Unraid"
  - "PLEX_URL=http://192.168.4.158:32400"
  - "SPOTIFY_USER_ID=xxx"
  - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - "LANG=C.UTF-8"
  - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
  - "PYTHON_VERSION=3.12.5"
  - "PYTHON_PIP_VERSION=24.2"
  - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66d8a0f637083e2c3ddffc0cb1e65ce126afb856/public/get-pip.py"
  - "PYTHON_GET_PIP_SHA256=6fb7b781206356f45ad79efbb19322caa6c2a5ad39092d0d44d0fec94117e118"
  - "PYTHONDONTWRITEBYTECODE=1"
  - "PYTHONUNBUFFERED=1"

hostname: "c8fd112b0b81"

image: "gyarbij/plexist:dev"

ipc: "private"

labels:
  net.unraid.docker.icon: "https://github.com/Gyarbij/Plexist/blob/main/assets/plexist.png"
  net.unraid.docker.managed: "dockerman"

logging:
  driver: "json-file"
  options:
    max-file: "1"
    max-size: "50m"

network_mode: "bridge"

user: "plexist"

volumes:
  - "/mnt/cache/appdata/plexist:/data"

working_dir: "/app"
```

pull the image again as there was a typo in the code that's been fixed by #68

**Comment by Eric-sson** [comment]
@Gyarbij 

I updated to the latest and changed the below variable and path.

environment:
  - "DB_PATH=/data/plexist.db"

volumes:
  - "/mnt/cache/appdata/plexist:/data"

But I am still getting the below and then the container stops.

Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 109, in <module>
    main()
  File "/app/plexist/plexist.py", line 72, in main
    initialize_db()
  File "/app/plexist/modules/plex.py", line 29, in initialize_db
    conn = sqlite3.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 109, in <module>
    main()
  File "/app/plexist/plexist.py", line 72, in main
    initialize_db()
  File "/app/plexist/modules/plex.py", line 29, in initialize_db
    conn = sqlite3.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

Below is the docker compose:

services:
  plexist:

    command:
      - "python"
      - "plexist/plexist.py"

    container_name: "plexist"

    environment:
      - "PLEX_URL=http://192.168.4.158:32400"
      - "SECONDS_TO_WAIT=604800"
      - "PUID=99"
      - "SPOTIFY_CLIENT_ID=xxxx"
      - "SPOTIFY_CLIENT_SECRET=xxxx"
      - "TZ=Europe/Paris"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "WRITE_MISSING_AS_CSV=1"
      - "PLEX_TOKEN=xxxx"
      - "ADD_PLAYLIST_POSTER=1"
      - "ADD_PLAYLIST_DESCRIPTION=1"
      - "UMASK=002"
      - "SPOTIFY_USER_ID=xxxx"
      - "DB_PATH=/data/plexist.db"
      - "HOST_CONTAINERNAME=plexist"
      - "APPEND_INSTEAD_OF_SYNC=1"
      - "PGID=100"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.12.5"
      - "PYTHON_PIP_VERSION=24.2"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66d8a0f637083e2c3ddffc0cb1e65ce126afb856/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=6fb7b781206356f45ad79efbb19322caa6c2a5ad39092d0d44d0fec94117e118"
      - "PYTHONDONTWRITEBYTECODE=1"
      - "PYTHONUNBUFFERED=1"

    hostname: "2c459cd97e08"

    image: "gyarbij/plexist:dev"

    ipc: "private"

    labels:
      net.unraid.docker.icon: "https://github.com/Gyarbij/Plexist/blob/main/assets/plexist.png"
      net.unraid.docker.managed: "dockerman"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    user: "plexist"

    volumes:
      - "/mnt/cache/appdata/plexist:/data"

    working_dir: "/app"

version: "3.6"
